# Generated by Django 4.0.6 on 2022-11-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField()),
                ('title', models.CharField(max_length=100, null=True)),
                ('text', models.TextField(null=True)),
            ],
        ),
    ]
